# 01 Data Collection

## Project question
Can we predict median private rent across local areas using economic and housing market indicators?

## Target variable
Average monthly private rent by local authority.

## Candidate features
- Median income
- Median house price
- Region
- Population density
- Unemployment rate

## First milestone
Create one merged dataset at local authority level.

In [6]:
from pathlib import Path
import pandas as pd

In [7]:
PROJECT_ROOT = Path("..").resolve()

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

RAW_DATA_DIR

PosixPath('/Users/robbie/rent-prediction-analysis/data/raw')

In [8]:
rent_path = RAW_DATA_DIR / "price_index_of_rents.xlsx"
house_price_path = RAW_DATA_DIR / "uk_hpi_average_prices_2026.csv"
income_path = RAW_DATA_DIR / "ashe_median_annual_pay_2025.csv"

In [9]:
house_prices = pd.read_csv(house_price_path)
income = pd.read_csv(income_path, skiprows = 9)

In [10]:
rent = pd.ExcelFile(rent_path)
rent.sheet_names

['Cover sheet', 'Contents', 'Notes', 'Table 1']

In [11]:
rents = pd.read_excel(rent_path, sheet_name="Table 1", header = 2)

In [12]:
rents.head()

,Time period,Area code,Area name,Region or country name,Index,Monthly change,Annual change,Rental price,Index one bed,Monthly change one bed,...,Annual change semidetached,Rental price semidetached,Index terraced,Monthly change terraced,Annual change terraced,Rental price terraced,Index flat maisonette,Monthly change flat maisonette,Annual change flat maisonette,Rental price flat maisonette
0,2015-01-01,K02000001,United Kingdom,[z],81.258259,[x],[x],910,82.339979,[x],...,[x],897,80.345118,[x],[x],893,83.26757,[x],[x],904
1,2015-02-01,K02000001,United Kingdom,[z],81.413747,0.191351,[x],912,82.53953,0.24235,...,[x],899,80.478716,0.166281,[x],894,83.457123,0.227644,[x],906
2,2015-03-01,K02000001,United Kingdom,[z],81.663685,0.306997,[x],915,82.781781,0.293496,...,[x],901,80.72993,0.312149,[x],897,83.73479,0.332706,[x],909
3,2015-04-01,K02000001,United Kingdom,[z],81.990506,0.400204,[x],918,83.232795,0.544823,...,[x],904,80.995081,0.328442,[x],900,84.194112,0.548543,[x],914
4,2015-05-01,K02000001,United Kingdom,[z],82.343646,0.430708,[x],922,83.597644,0.438349,...,[x],908,81.33684,0.421951,[x],904,84.638073,0.527307,[x],918

In [13]:
income.head()

,local authority: district / unitary (as of April 2023),Annual pay - gross,Conf %
0,Hartlepool,28830,6.7
1,Middlesbrough,30253,5.5
2,Redcar and Cleveland,28630,6.5
3,Stockton-on-Tees,29877,6.9
4,Darlington,30100,8.4

In [14]:
income.shape

(362, 3)

In [15]:
income.dtypes

local authority: district / unitary (as of April 2023)    object
Annual pay - gross                                        object
Conf %                                                    object
dtype: object

In [16]:
house_prices.columns

Index(['Date', 'Region_Name', 'Area_Code', 'Average_Price', 'Monthly_Change',
       'Annual_Change', 'Average_Price_SA'],
      dtype='object')

In [17]:
house_prices.head()

,Date,Region_Name,Area_Code,Average_Price,Monthly_Change,Annual_Change,Average_Price_SA
0,1968-04-01,Northern Ireland,N92000002,3465,NaN,NaN,NaN
1,1968-04-01,England,E92000001,3218,NaN,NaN,NaN
2,1968-04-01,Wales,W92000004,2732,NaN,NaN,NaN
3,1968-04-01,Scotland,S92000003,2738,NaN,NaN,NaN
4,1968-04-01,London,E12000007,4730,NaN,NaN,NaN

In [18]:
house_prices.describe()

       Average_Price  Monthly_Change  Annual_Change  Average_Price_SA
count   1.507050e+05   150252.000000  145845.000000       5304.000000
mean    1.844009e+05        0.519911       6.042084     169966.067308
std     1.318734e+05        1.930316       8.597213      95528.518749
min     2.553000e+03      -30.300000     -35.800000      39008.000000
25%     1.012050e+05       -0.500000       1.100000     116865.750000
50%     1.559170e+05        0.500000       5.000000     153743.500000
75%     2.321950e+05        1.400000      10.000000     211049.500000
max     1.656986e+06       35.300000      98.400000     574627.000000

In [19]:
income = income.dropna(subset=["local authority: district / unitary (as of April 2023)"])

In [20]:
income.isna().sum()

local authority: district / unitary (as of April 2023)    0
Annual pay - gross                                        0
Conf %                                                    2
dtype: int64

In [21]:
rents_clean = rents[["Time period", "Area code", "Area name", "Rental price","Region or country name"]].copy()

In [22]:
rents_clean.head()

  Time period  Area code       Area name Rental price Region or country name
0  2015-01-01  K02000001  United Kingdom          910                    [z]
1  2015-02-01  K02000001  United Kingdom          912                    [z]
2  2015-03-01  K02000001  United Kingdom          915                    [z]
3  2015-04-01  K02000001  United Kingdom          918                    [z]
4  2015-05-01  K02000001  United Kingdom          922                    [z]

In [23]:
income.head()

,local authority: district / unitary (as of April 2023),Annual pay - gross,Conf %
0,Hartlepool,28830,6.7
1,Middlesbrough,30253,5.5
2,Redcar and Cleveland,28630,6.5
3,Stockton-on-Tees,29877,6.9
4,Darlington,30100,8.4

In [24]:
house_prices.head()

,Date,Region_Name,Area_Code,Average_Price,Monthly_Change,Annual_Change,Average_Price_SA
0,1968-04-01,Northern Ireland,N92000002,3465,NaN,NaN,NaN
1,1968-04-01,England,E92000001,3218,NaN,NaN,NaN
2,1968-04-01,Wales,W92000004,2732,NaN,NaN,NaN
3,1968-04-01,Scotland,S92000003,2738,NaN,NaN,NaN
4,1968-04-01,London,E12000007,4730,NaN,NaN,NaN

### Income dataset notes

- Geography appears to be local authority district/unitary.
- Area column: `local authority: district / unitary (as of April 2023)`
- Value column: `Annual pay - gross`
- Confidence column: `Conf %`
- No area code included in this export.

## Create cleaned starter datasets

In [33]:
rent_apr_2026 = rents_clean[rents_clean["Time period"] == "2026-04-01"].copy()

rent_apr_2026 = rent_apr_2026.rename(columns={
    "Time period": "date",
    "Area code": "area_code",
    "Area name": "area_name",
    "Rental price": "average_monthly_rent",
    "Region or country name": "region"

})

rent_apr_2026.head()

          date  area_code       area_name average_monthly_rent region
135 2026-04-01  K02000001  United Kingdom                 1381    [z]
272 2026-04-01  K03000001   Great Britain                 1393    [z]
409 2026-04-01  E92000001         England                 1438    [z]
546 2026-04-01  W92000004           Wales                  834    [z]
683 2026-04-01  S92000003        Scotland                 1019    [z]

In [35]:
house_prices_apr_2026 = house_prices[house_prices["Date"] == "2026-04-01"].copy()

house_prices_apr_2026 = house_prices_apr_2026.rename(columns={
    "Date": "date",
    "Region_Name": "area_name",
    "Area_Code": "area_code",
    "Region or country name": "region",
    "Average_Price": "average_house_price"

})

house_prices_apr_2026 = house_prices_apr_2026[
    ["date", "area_code", "area_name", "average_house_price"]
]

house_prices_apr_2026.head()

              date  area_code         area_name  average_house_price
150300  2026-04-01  S92000003          Scotland               191927
150301  2026-04-01  W92000004             Wales               212489
150302  2026-04-01  E92000001           England               291445
150303  2026-04-01  N92000002  Northern Ireland               198015
150304  2026-04-01  E13000001      Inner London               623219

In [29]:
income_clean = income.rename(columns={
    "local authority: district / unitary (as of April 2023)": "area_name",
    "Annual pay - gross": "median_annual_pay",
    "Conf %": "income_confidence_pct"
})

income_clean["median_annual_pay"] = pd.to_numeric(
    income_clean["median_annual_pay"],
    errors="coerce"
)

income_clean.head()

              area_name  median_annual_pay income_confidence_pct
0            Hartlepool            28830.0                   6.7
1         Middlesbrough            30253.0                   5.5
2  Redcar and Cleveland            28630.0                   6.5
3      Stockton-on-Tees            29877.0                   6.9
4            Darlington            30100.0                   8.4

In [36]:
rent_apr_2026.to_csv(PROCESSED_DATA_DIR / "rent_apr_2026.csv", index=False)
house_prices_apr_2026.to_csv(PROCESSED_DATA_DIR / "house_prices_apr_2026.csv", index=False)
income_clean.to_csv(PROCESSED_DATA_DIR / "income_2025.csv", index=False)